name: 'PHP Compatibility'
on: workflow_call
permissions:
  contents: read
jobs:
  phpcs-compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup third party repos with composer
        env:
          LICENSE_GRAVITY_FORMS: ${{ secrets.LICENSE_GRAVITY_FORMS }}
          LICENSE_BEAVER_BUILDER: ${{ secrets.LICENSE_BEAVER_BUILDER }}
        run: |
          composer config --global http-basic.composer.gravity.io $LICENSE_GRAVITY_FORMS https://github-ci.gf.local
          composer config --global repositories.beaver-builder composer "https://composer.wpbeaverbuilder.com/$LICENSE_BEAVER_BUILDER"
      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v3
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          PHPCS_STANDARD_FILE_NAME: .phpcs.compat.xml
