name: 'PHP Compatibility'
on: workflow_call
permissions:
  contents: read
jobs:
  phpcs-compatibility:
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repository
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v7
      # ------------------------------------------------------------------------------
      # Setup third party repos
      # ------------------------------------------------------------------------------
      - name: Setup third party repos with composer
        env:
          LICENSE_GRAVITY_FORMS: ${{ secrets.LICENSE_GRAVITY_FORMS }}
          LICENSE_BEAVER_BUILDER: ${{ secrets.LICENSE_BEAVER_BUILDER }}
        run: |
          if [ -n "$LICENSE_GRAVITY_FORMS" ]; then
          composer config --global http-basic.composer.gravity.io $LICENSE_GRAVITY_FORMS https://github-ci.gf.local
          fi
          if [ -n "$LICENSE_BEAVER_BUILDER" ]; then
          composer config --global repositories.beaver-builder composer "https://composer.wpbeaverbuilder.com/$LICENSE_BEAVER_BUILDER"
          fi
      # ------------------------------------------------------------------------------
      # Install dependencies - ignoring php requirements
      # ------------------------------------------------------------------------------
      - name: Install dependencies
        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0
        with:
          composer-options: "--ignore-platform-reqs --no-scripts"
      # ------------------------------------------------------------------------------
      # PHPCS compatibility
      # ------------------------------------------------------------------------------
      - name: Run PHPCS compatibility inspection
        uses: rtCamp/action-phpcs-code-review@v3
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          PHPCS_STANDARD_FILE_NAME: .phpcs.compat.xml
