name: 'PHP CodeSniffer'
on: workflow_call
permissions:
  contents: read
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repository
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # ------------------------------------------------------------------------------
      # Get the changed files in a space separated list.
      # ------------------------------------------------------------------------------
      - name: Get all changed files and use a space separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          separator: " "
          files: |
            **.php
      # ------------------------------------------------------------------------------
      # Prepare our cache directories
      # ------------------------------------------------------------------------------
      - name: Get Composer Cache Directory
        id: get-composer-cache-dir
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      # ------------------------------------------------------------------------------
      # Set up PHP and run phpstan
      # ------------------------------------------------------------------------------
      - name: Configure PHP environment to run phpstan
        uses: "shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f" # 2.37.0
        with:
          php-version: 8.0
      # ------------------------------------------------------------------------------
      # Override composer php version
      # ------------------------------------------------------------------------------
      - name: Set php version ${{ matrix.phpVersion }} in composer
        run: composer config platform.php ${{ matrix.phpVersion }}
      - name: Setup third party repos with composer
        env:
          LICENSE_GRAVITY_FORMS: ${{ secrets.LICENSE_GRAVITY_FORMS }}
          LICENSE_BEAVER_BUILDER: ${{ secrets.LICENSE_BEAVER_BUILDER }}
        run: |
          composer config --global http-basic.composer.gravity.io $LICENSE_GRAVITY_FORMS https://github-ci.gf.local
          composer config --global repositories.beaver-builder composer "https://composer.wpbeaverbuilder.com/$LICENSE_BEAVER_BUILDER"
      # ------------------------------------------------------------------------------
      # Install dependencies - ignoring php requirements
      # ------------------------------------------------------------------------------
      - name: Install dependencies
        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0
        with:
          composer-options: "--ignore-platform-reqs --no-scripts"
      # ------------------------------------------------------------------------------
      # Setup file permissions
      # ------------------------------------------------------------------------------
      - name: "Setup file permissions"
        run: |
          sudo chown -R root:root $GITHUB_WORKSPACE
      # ------------------------------------------------------------------------------
      # PHPCS via reviewdog
      # ------------------------------------------------------------------------------
      - name: Setup reviewdog
        uses: "reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f" # 1.5.0
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
          vendor/bin/phpcs --report=json ${{ steps.changed-files.outputs.all_changed_files }} | jq -r ' .files | to_entries[] | .key as $path | .value.messages[] as $msg | "\($path):\($msg.line):\($msg.column):`\($msg.source)`<br>\($msg.message)" ' | reviewdog -efm="%f:%l:%c:%m" -name="phpcs" -filter-mode="added" -fail-on-error=true -reporter=github-pr-review
