name: 'PHP Static Analysis'
on: workflow_call
permissions:
  contents: read
jobs:
  phpstan:
    strategy:
      matrix:
        phpVersion: [
          "8.0",
          "8.1",
          "8.2",
          "8.3"
        ]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repository
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v6
      # ------------------------------------------------------------------------------
      # Get the changed files in a space separated list.
      # ------------------------------------------------------------------------------
      - name: Get all changed files and use a space separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          separator: " "
          files: |
            **.php
      # ------------------------------------------------------------------------------
      # Set up PHP and run phpstan
      # ------------------------------------------------------------------------------
      - name: Configure PHP environment to run phpstan
        uses: "shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f" # 2.37.0
        with:
          php-version: ${{ matrix.phpVersion }}
          tools: composer:v2
      # ------------------------------------------------------------------------------
      # Override composer php version
      # ------------------------------------------------------------------------------
      - name: Set php version ${{ matrix.phpVersion }} in composer
        run: composer config platform.php ${{ matrix.phpVersion }}
      - name: Setup third party repos with composer
        env:
          LICENSE_GRAVITY_FORMS: ${{ secrets.LICENSE_GRAVITY_FORMS }}
          LICENSE_BEAVER_BUILDER: ${{ secrets.LICENSE_BEAVER_BUILDER }}
        run: |
          composer config --global http-basic.composer.gravity.io $LICENSE_GRAVITY_FORMS https://github-ci.gf.local
          composer config --global repositories.beaver-builder composer "https://composer.wpbeaverbuilder.com/$LICENSE_BEAVER_BUILDER"
      # ------------------------------------------------------------------------------
      # Install dependencies - ignoring php requirements
      # ------------------------------------------------------------------------------
      - name: Install dependencies
        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0
        with:
          composer-options: "--ignore-platform-reqs --no-scripts"
      # ------------------------------------------------------------------------------
      # Run phpstan
      # ------------------------------------------------------------------------------
      - name: Run phpstan
        run: ./vendor/bin/phpstan analyse --error-format=table -c phpstan.neon ${{ steps.changed-files.outputs.all_changed_files }}
